void_events = ('gameEventTriggered',
               'onClientResourceStart',
               'onClientResourceStop',
               'onClientMapStart',
               'onResourceStart',
               'onResourceStarting',
               'onResourceStop',
               'playerConnecting',
               'playerDropped',
               'populationPedCreating',
               'rconCommand',
               'playerSpawned',  # The following may not be a native event?
               'cron:runAt',
               'chatMessage',
               'chat:addMessage',
               'baseevents:onPlayerDied',
               'baseevents:onPlayerKilled',
               'baseevents:onPlayerWasted',
               'baseevents:onPlayerDied',
               'baseevents:onPlayerKilled',
               'baseevents:onPlayerWasted',
               'baseevents:enteringVehicle',
               'baseevents:enteringAborted',
               'baseevents:enteredVehicle',
               'baseevents:leftVehicle',
               'chat:addSuggestion',
               'chat:addSuggestions',
               'chat:removeSuggestion',
               'chat:addTemplate',
               'chat:clear'
               )

events = (r'ESX.TriggerServerCallback\([\'|"](.*?)[\'|"]',
          r'ESX.RegisterServerCallback\([\'|"](.*?)[\'|"]',
          r'RegisterNetEvent\([\'|"](.*?)[\'|"]',
          r'RegisterServerEvent\([\'|"](.*?)[\'|"]',
          r'TriggerEvent\([\'|"](.*?)[\'|"]',
          r'TriggerClientEvent\([\'|"](.*?)[\'|"]',
          r'TriggerServerEvent\([\'|"](.*?)[\'|"]',
          r'AddEventHandler\([\'|"](.*?)[\'|"]',
          r'ESX.TriggerServerCallback\(\s+[\'|"](.*?)[\'|"]',  # From this line onwards, starts checking for line breaks
          r'ESX.RegisterServerCallback\(\s+[\'|"](.*?)[\'|"]',
          r'RegisterNetEvent\(\s+[\'|"](.*?)[\'|"]',
          r'RegisterServerEvent\(\s+[\'|"](.*?)[\'|"]',
          r'TriggerEvent\(\s+[\'|"](.*?)[\'|"]',
          r'TriggerClientEvent\(\s+[\'|"](.*?)[\'|"]',
          r'TriggerServerEvent\(\s+[\'|"](.*?)[\'|"]',
          r'AddEventHandler\(\s+[\'|"](.*?)[\'|"]'
          )
